training_data = [
    ("I love this app", "positive"),
    ("I feel so lost and overwhelmed", "negative"),
    ("Today was very peaceful", "positive"),
    ("I'm just tired", "neutral"),
    ("I hate my life so much", "negative"),
    ("I am so happy, I just passed my test!", "joy"),
    ("I am so scared to go outside tonight", "fear"),
    ("I am having a pretty decent day today", "stable"),
    ("I'm just so tired but I am okay though", "Stable"),
    ("Today I had a vision of my father beating me", "ptsd"),
    ("I just can't focus", "adhd"),
    ("Life is so draining at times, I don't know if I can do this anymore", "depression"),
    ("I love how my mom gave me a warm hug today. That really made me feel good", "positive"),
    ("I am feeling very lonely even in a crowd", "lonely"),
    ("My chest is tight and I can't stop shaking", "anxiety"),
    ("Every time I close my eyes, I see the accident again", "ptsd"),
    ("Why does everything have to be so difficult for me to understand?", "adhd"),
    ("I felt like I was on top of the world today", "euphoria"),
    ("I'm proud of myself for setting boundaries", "growth"),
    ("I want to scream but nothing comes out", "frustration"),
    ("I feel numb, like nothing matters anymore", "depression"),
    ("My thoughts are racing and I can't slow them down", "anxiety"),
    ("I get so distracted, I just can't seem to get anything done", "adhd"),
    ("I miss my dad so much it hurts to breathe", "grief"),
    ("I feel like a burden to everyone in my family", "depression"),
    ("Why can't I just be normal for once?", "self-doubt"),
    ("I had a flashback today and it left me shaking", "ptsd"),
    ("I feel like I'm failing at everything", "self-doubt"),
    ("I couldn't get out of bed today", "depression"),
    ("I feel like I'm constantly being watched", "paranoia"),
    ("I am si angry all the time and I don't even know why", "anger"),
    ("I finally asked for help and it felt good", "growth"),
    ("I feel motivated to try again", "hopeful"),
    ("I had a great conversation with my friend today", "positive"),
    ("I feel like I am finally healing", "growth"),
    ("My hands won't stop trembling", "anxiety"),
    ("I want to run away from everything", "distress"),
    ("I think I want to hurt myself", "danger"),
    ("I want to kill myself today", "suicidal"),
    ("I can't sleep because my mind won't stop", "insomnia"),
    ("It feels like the world is caving in on me", "panic"),
    ("I finally cleaned my room after weeks", "accomplishment"),
    ("I talked to my therapist and felt lighter", "relief"),
    ("I keep forgetting things I was just told", "adhd"),
    ("Music is the only thing that keeps me going", "coping"),
    ("Sometimes I feel like I'm not even real", "dissociation"),
    ("I'm excited to start my new job tomorrow", "hopeful"),
    ("I cried today but it felt like a release", "relief"),
    ("The nightmares won't go away", "ptsd"),
    ("I laughed so hard I cried today", "joy"),
    ("No one understands me an I feel so alone", "lonely"),
    ("I finally forgave myself", "growth"),
    ("I'm scared I might do something I regret", "danger"),
    ("Today I didn't feel anxious for once", "stable"),
    ("I'm exhausted from pretending to be okay", "masking"),
    ("I keep imagining ways to end my life", "suicidal"),
    ("I don't trust anyone, everyone's out to get me", "paranoia"),
    ("I'm always angry and it ruins my relationships", "anger"),
    ("I felt like I could fly today, everything was perfect", "euphoria"),
    ("I achieved all my goals today and it felt amazing", "accomplishment"),
    ("I listened to music to get through another rough day", "coping"),
    ("Talking to my best friend helped me breathe again", "relief"),
    ("I stayed in bed thinking about ending it all", "suicidal"),
    ("Every sound feels like a threat", "panic"),
    ("I’m afraid I might snap and hurt someone", "danger"),
    ("I lie about being okay so no one asks questions", "masking"),
    ("Sometimes I forget where I am or who I’m with", "dissociation"),
    ("I looked at my dad’s photo and cried for hours", "grief"),
    ("Why do I always doubt my worth?", "self-doubt"),
    ("I finally fell asleep after days of tossing and turning", "insomnia"),
    ("I woke up gasping and drenched in sweat again", "panic"),
    ("I'm tired of pretending to smile", "masking"),
    ("The pain inside just won’t go away", "suicidal"),
    ("It felt good to scream into my pillow", "relief"),
    ("I journaled today to help process my feelings", "coping")
]